spring:
  graphql:
    graphiql:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:graphql_db
    username: graph
    password:
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: false
    show-sql: true
    properties:
      '[format_sql]': true
    open-in-view: false
